import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./store/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopzen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="max-w-[1536px] mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
