import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopzen",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ paddingTop: "64px" }}>
        <Navbar />
        <div className="max-w-[1536px] mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
